### ISSUE TITLE
Set toast duration.

### ISSUE THREAD

**Issue by ghost** [onurkagan/KToast#2]
Hi!
First of all it's a very nice library, thanks!

For me, LENGTH_SHORT is still too long, is there any way to make it shorter?

**Comment by onurkagan** [comment]
Hi, thank you for your comment.

Library have just three time option; short, long and auto. But i will work about custom time option. This is a good idea. Thanks.

**Comment by onurkagan** [comment]
https://github.com/onurkagan/KToast/issues/7
